[package]
name = "tlse"
version = "0.1.0"
edition = "2021"

[dependencies]

[build-dependencies]
bindgen = "0.70.1"
cc = "1.2.2"

[dev-dependencies]
criterion = "0.5.1"

[profile.release]
debug = true

[[bench]]
name = "bench_export"
path = "benches/bench_export.rs"
harness = false